name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        build:
          context: .
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl -f http://localhost:8000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          curl --fail http://localhost:8000 || exit 1

      - name: Run UI test
        run: |
          curl --fail http://localhost:8000 | grep "<form" || exit 1
